/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class online_ruin_of_future_nameless_chess_CppSync */

#ifndef _Included_online_ruin_of_future_nameless_chess_CppSync
#define _Included_online_ruin_of_future_nameless_chess_CppSync
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     online_ruin_of_future_nameless_chess_CppSync
 * Method:    sync_move
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_online_ruin_1of_1future_nameless_1chess_CppSync_sync_1move
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     online_ruin_of_future_nameless_chess_CppSync
 * Method:    sync_gamemode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_online_ruin_1of_1future_nameless_1chess_CppSync_sync_1gamemode
  (JNIEnv *, jobject, jint);

/*
 * Class:     online_ruin_of_future_nameless_chess_CppSync
 * Method:    sync_nothing
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_online_ruin_1of_1future_nameless_1chess_CppSync_sync_1nothing
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
